services:
  database:
    image: 'postgres'
    container_name: 'local-postgres'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=scrapes
    volumes:
      # - ./mongo-volume/:/data/db
      - data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
